version: '3.8'

services:
  web:
    image: backend_test  
    build: .
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - mongo

  mongo:
    image: mongodb/mongodb-community-server:6.0-ubi8
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
  
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
      
volumes:
  mongo-data:
